export interface PrintSizeDefinition {
  id: string;
  name: string;
  category: "photo" | "document" | "poster" | "passport";
  widthIn: number;
  heightIn: number;
  widthCm: number;
  heightCm: number;
  aspectRatioLabel: string;
  typicalUse: string;
}

export const STANDARD_PRINT_SIZES: PrintSizeDefinition[] = [
  // Photo prints
  {
    id: "4x6",
    name: "4 × 6 in",
    category: "photo",
    widthIn: 4,
    heightIn: 6,
    widthCm: 10.16,
    heightCm: 15.24,
    aspectRatioLabel: "3:2",
    typicalUse: "Most popular standard album print (DSLR native)",
  },
  {
    id: "5x7",
    name: "5 × 7 in",
    category: "photo",
    widthIn: 5,
    heightIn: 7,
    widthCm: 12.7,
    heightCm: 17.78,
    aspectRatioLabel: "7:5",
    typicalUse: "Framed desktop & greeting card size",
  },
  {
    id: "8x10",
    name: "8 × 10 in",
    category: "photo",
    widthIn: 8,
    heightIn: 10,
    widthCm: 20.32,
    heightCm: 25.4,
    aspectRatioLabel: "5:4",
    typicalUse: "Standard portrait frame & wall photo",
  },
  {
    id: "8.5x11",
    name: "8.5 × 11 in (Letter)",
    category: "document",
    widthIn: 8.5,
    heightIn: 11,
    widthCm: 21.59,
    heightCm: 27.94,
    aspectRatioLabel: "1.29:1",
    typicalUse: "Standard US home printer document size",
  },
  {
    id: "11x14",
    name: "11 × 14 in",
    category: "photo",
    widthIn: 11,
    heightIn: 14,
    widthCm: 27.94,
    heightCm: 35.56,
    aspectRatioLabel: "14:11",
    typicalUse: "Small gallery wall frame",
  },
  {
    id: "12x18",
    name: "12 × 18 in",
    category: "poster",
    widthIn: 12,
    heightIn: 18,
    widthCm: 30.48,
    heightCm: 45.72,
    aspectRatioLabel: "3:2",
    typicalUse: "Medium wall poster (matches 3:2 camera ratio)",
  },
  {
    id: "16x20",
    name: "16 × 20 in",
    category: "poster",
    widthIn: 16,
    heightIn: 20,
    widthCm: 40.64,
    heightCm: 50.8,
    aspectRatioLabel: "5:4",
    typicalUse: "Large wall art & canvas print",
  },
  {
    id: "20x30",
    name: "20 × 30 in",
    category: "poster",
    widthIn: 20,
    heightIn: 30,
    widthCm: 50.8,
    heightCm: 76.2,
    aspectRatioLabel: "3:2",
    typicalUse: "Feature wall poster",
  },
  {
    id: "24x36",
    name: "24 × 36 in",
    category: "poster",
    widthIn: 24,
    heightIn: 36,
    widthCm: 60.96,
    heightCm: 91.44,
    aspectRatioLabel: "3:2",
    typicalUse: "Movie poster & large commercial display",
  },

  // ISO A-Series
  {
    id: "a6",
    name: "A6 (10.5 × 14.8 cm)",
    category: "document",
    widthIn: 4.13,
    heightIn: 5.83,
    widthCm: 10.5,
    heightCm: 14.8,
    aspectRatioLabel: "√2 (1.41:1)",
    typicalUse: "Postcards & small brochures",
  },
  {
    id: "a5",
    name: "A5 (14.8 × 21.0 cm)",
    category: "document",
    widthIn: 5.83,
    heightIn: 8.27,
    widthCm: 14.8,
    heightCm: 21.0,
    aspectRatioLabel: "√2 (1.41:1)",
    typicalUse: "Notebooks & flyer handouts",
  },
  {
    id: "a4",
    name: "A4 (21.0 × 29.7 cm)",
    category: "document",
    widthIn: 8.27,
    heightIn: 11.69,
    widthCm: 21.0,
    heightCm: 29.7,
    aspectRatioLabel: "√2 (1.41:1)",
    typicalUse: "Standard international paper & certificates",
  },
  {
    id: "a3",
    name: "A3 (29.7 × 42.0 cm)",
    category: "poster",
    widthIn: 11.69,
    heightIn: 16.54,
    widthCm: 29.7,
    heightCm: 42.0,
    aspectRatioLabel: "√2 (1.41:1)",
    typicalUse: "Office poster & presentation drawings",
  },
  {
    id: "a2",
    name: "A2 (42.0 × 59.4 cm)",
    category: "poster",
    widthIn: 16.54,
    heightIn: 23.39,
    widthCm: 42.0,
    heightCm: 59.4,
    aspectRatioLabel: "√2 (1.41:1)",
    typicalUse: "Art exhibition & architectural prints",
  },

  // Passport & ID
  {
    id: "passport-us",
    name: "2 × 2 in (US Passport)",
    category: "passport",
    widthIn: 2,
    heightIn: 2,
    widthCm: 5.08,
    heightCm: 5.08,
    aspectRatioLabel: "1:1",
    typicalUse: "US Passport & Visa photo specification",
  },
  {
    id: "passport-eu",
    name: "35 × 45 mm (EU / UK / BD)",
    category: "passport",
    widthIn: 1.38,
    heightIn: 1.77,
    widthCm: 3.5,
    heightCm: 4.5,
    aspectRatioLabel: "7:9",
    typicalUse: "UK, EU, Schengen & Bangladesh passport standard",
  },
];
